### ISSUE TITLE
Missing test files?

### ISSUE THREAD

**Issue by FedericoCeratto** [pascalkuthe/termini#4]
Hello and thanks for developing termini. It seems to me that the test files are not in the crate while the `tests.rs` file is there, making most tests fail.
Thanks!

**Comment by pascalkuthe** [comment]
The test files are all in the repo. Do you mean on the crates.io release? That's intentional not to bloat the crate with a ton of (fairly large) test data. It's unusual to run tests on published crates.io libraries. What would be your usecase for that?

**Comment by FedericoCeratto** [comment]
@pascalkuthe thanks for the answer. I am packaging the crate for Debian and it's very common to run tests both for individual packages but also to test integration across packages.

**Comment by FedericoCeratto** [comment]
I patched in a handful of files to pass all tests without modification. The Debian package is being uploaded so I'm closing this issue. Thanks!
